version: "3.9"
services:
  api:
    build: ./Backend
    restart: always
    environment:
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      PORT: ${PORT}
    ports:
      - "8080:80"
    command: npm run start
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    volumes:
      - beer-swipe-vol:/var/lib/postgresql/data

  sveltekit:
    build: ./Frontend
    ports:
      - "3000:5173"
    #    environment:
    #      NODE_ENV: production
    command: npm run dev -- --host

volumes:
  beer-swipe-vol:


