version: "3.9"
name: beer-swipe
services:
  api:
    build: ./Backend
    restart: always
    environment:
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      APIURL: ${APIURL}
      APIPORT: ${APIPORT}
      DBURL: ${DOCKERDBURL}
      DBPORT: ${DBPORT}
      FEURL: ${FEURL}
      FEPORT: ${FEPORT}
      DOCKERFEURL: ${DOCKERFEURL}
    ports:
      - ${APIPORT}:${APIPORT}
    command: npm run start
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    ports:
      - ${DBPORT}:${DBPORT}
    volumes:
      - beer-swipe-vol:/var/lib/postgresql/data

  sveltekit:
    build: ./Frontend
    ports:
      - ${FEPORT}:5173
    environment:
      APIURL: ${DOCKERAPIURL}
      APIPORT: ${APIPORT}
#      NODE_ENV: production
    command: npm run dev -- --host

volumes:
  beer-swipe-vol:


