version: "3.9"
name: beer-swipe
services:
  api:
    build: ./Backend
    restart: always
    environment:
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      APIURL: ${APIURL}
      APIPORT: ${APIPORT}
      DBURL: ${DOCKERDBURL}
      DBPORT: ${DBPORT}
      FEURL: ${FEURL}
      FEPORT: ${FEPORT}
      DOCKERFEURL: ${DOCKERFEURL}
      TOKEN_SECRET: ${TOKEN_SECRET}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_TLS_REJECT_UNAUTHORIZED: ${SMTP_TLS_REJECT_UNAUTHORIZED}
      EMAIL_FROM: ${EMAIL_FROM}
    ports:
      - ${APIPORT}:${APIPORT}
    command: npm run start
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    ports:
      - ${DBPORT}:${DBPORT}
    volumes:
      - beer-swipe-vol:/var/lib/postgresql/data

  sveltekit:
    build: ./Frontend
    ports:
      - ${FEPORT}:5173
    environment:
      VITE_APIURL: ${APIURL}
      VITE_APIPORT: ${APIPORT}
    #      NODE_ENV: production
    command: npm run dev -- --host

volumes:
  beer-swipe-vol:


