version: "3.9"
name: beer-swipe
services:
  api:
    build: ./Backend
    restart: always
    environment:
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      APIURL: ${APIURL}
      APIPORT: ${APIPORT}
      DBURL: ${DOCKERDBURL}
      DBPORT: ${DBPORT}
      FEURL: ${FEURL}
      FEPORT: ${FEPORT}
      DOCKERFEURL: ${DOCKERFEURL}
      TOKEN_SECRET: ${TOKEN_SECRET}
      NODE_ENV: ${ENVIRONMENT}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_TLS_REJECT_UNAUTHORIZED: ${SMTP_TLS_REJECT_UNAUTHORIZED}
      EMAIL_FROM: ${EMAIL_FROM}
    ports:
      - ${APIPORT}:${APIPORT}
    command: npm run start
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    ports:
      - ${DBPORT}:${DBPORT}
    volumes:
      - beer-swipe-vol:/var/lib/postgresql/data
  test:
    build: ./Backend
    environment:
      PGPASSWORD: ${PGPASSWORD_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      DBURL: ${DBURL_TEST}
      DBPORT: ${DBPORT}
      FEURL: ${FEURL}
      FEPORT: ${FEPORT}
      DOCKERFEURL: ${DOCKERFEURL}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_TLS_REJECT_UNAUTHORIZED: ${SMTP_TLS_REJECT_UNAUTHORIZED}
      EMAIL_FROM: ${EMAIL_FROM}
    command: npm run test
  db-test:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
    ports:
      - ${DBPORT_TEST}:${DBPORT}
    volumes:
      - beer-swipe-test-vol:/var/lib/postgresql/data
  sveltekit:
    build:
      context: ./Frontend
    ports:
      - ${FEPORT}:4173
    environment:
      VITE_APIURL: ${APIURL}
      VITE_APIPORT: ${APIPORT}
    command: npm run preview -- --host

volumes:
  beer-swipe-vol:
  beer-swipe-test-vol:


