version: "3.9"
services:
  api:
    build: ..
    restart: always
    environment:
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    ports:
      - "8080:80"
    command: npm run start
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    volumes:
      - beer-swipe-vol:/var/lib/postgresql/data
volumes:
  beer-swipe-vol: