FROM node:22-alpine3.19

# Install dependencies for skia-canvas
RUN apk update && apk add fontconfig

# Setting up the work directory
WORKDIR /usr/src/app

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

# Exposing server port
EXPOSE 8080

# Command to run the application
CMD ["node", "app.js"]
