FROM node:12-alpine3.14

# Install dependencies for skia-canvas
RUN apk update && \
    apk add --no-cache \
    fontconfig \
    && rm -rf /var/cache/*

# Setting up the work directory
WORKDIR /usr/src/app

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

# Exposing server port
EXPOSE 8080

# Command to run the application
CMD ["node", "server.js"]
